version: '4'

services:
  frontend:
    build:
      context: ./frontend
    image: cms_management/frontend:v1.0.0
    container_name: frontend_container
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_CONTAINER_PORT}"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: cms_management/backend:v1.0.0
    container_name: backend_container
    ports:
      - "${BACKEND_PORT}:${BACKEND_CONTAINER_PORT}"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${DB_PORT}/${POSTGRES_DB}

  db:
    image: postgres:latest
    container_name: database_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_CONTAINER_PORT}"

networks:
  default:
    driver: bridge
