version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    image: frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: backend
    container_name: backend_container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL = postgresql://postgres:123456@db:5432/cms_management

  db:
    image: postgres:16
    container_name: database_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cms_management
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
